agent:
    #Data collection paremeters
    isput: False                         
    #Put or Call: {True,False}
    moneyness: "ATM"                     
    #Moneyness options: {"ATM","ITM","OTM"}
    prepro_stock: "Log"                  
    #Price preprocessing {Log, Log-moneyness, Nothing}
    backtest: False                      
    #Backtest only includes inference procedure for real data

    #First layer of parameters 
    network: "RNNFNN"             
    #Neural network architecture {"LSTM","RNNFNN","FFNN"}
    state_space: "Reduced_2"               
    #State space considered in the RL framework {"Full","Reduced_1","Reduced_2"}
    cash_constraint: True                
    #Boolean variable to include cash constraints {True,False}
    constraint_max: 100                  
    #Cash constraint limit (positive number)
    batch_size: 1000                 
    #batch size {296,1000} 
    nbs_units: 56                   
    #neurons per layer/cell
    loss_type: "CVaR"               
    #loss function {"CVaR","MSE","SMSE"}
    lr: 0.0005               
    #learning rate of the Adam optimizer
    dropout_par: 0.5                  
    #dropout regularization parameter 

    #Second layer of parameters
    transaction_cost: 0                   
    #Proportional transaction cost [0,5/10000,5/1000,1/100]
    riskaversion: 0.95                 
    #CVaR confidence level (0,1)
    epochs: 50                    
    #Number of epochs, training iterations 

    # Third layer of parameters
    display_plot: False                 
    #Display plot of training and validation loss
    display_metrics: True
    #Display metrics based on estimated values of penalty functions
    #["Avg-HE","CVaR:95%","CVaR:99%","MSE","SMSE","Delta-CVaR:95%"]




